CoreELEC/CoreELEC

projects/Amlogic/bootloader/update.sh
I'm sending this change as a PR as it is a significant change to the update process and I would like to get others opinions on it.
There is a lot of users who ignore instructions given for how to update and manually place DTB images in the update folder before updating and this prevents them from receiving the latest DTB.
If no DTB is placed in the update folder then the update process will flash /usr/share/bootloader/$LE_DT_ID.img over the current DTB however if a DTB is placed in the update folder then this does not occur.
I have changed this so *.dtb is ignored in the update folder and the update process can only be overridden if the DTB is named dtb.override.img in the update folder so we can still test DTB changes for development purposes easily.
=> projects/Amlogic: update DTB upgrade priority

config/addon/xbmc.broken.xml, config/addon/xbmc.python.module.xml, config/addon/xbmc.python.script.xml, config/addon/xbmc.service.library.xml, config/addon/xbmc.service.pluginsource.xml, config/addon/xbmc.service.xml, packages/addons/script/script.config.vdr/sources/addon.xml, packages/addons/service/touchscreen/addon.xml, packages/addons/service/tvheadend42/addon.xml, packages/addons/service/tvheadend44/addon.xml
There is a bug within Kodi that seems to not recognize the os.libreelec.tv dependency within addon's even though it exists on the system.
This gives the false impression to the users that they are missing a dependency when they are not.
=> config/packages: remove os.libreelec dependency

packages/mediacenter/kodi/patches/amlogic/kodi-ce-105-default-kodi-resolution.patch
Sometimes after reboot or power on kodi didn't receive resolutions from TV and set it by default to 720p.
After this change default resolution is 1080p
=> Change default kodi resolution to 1080p

scripts/checkdeps
Today I've created a new ArchLinux virtual machine from scratch and I've found that rpcgen command moved out from libc package to rpcsvc-proto package. I've created a simple commit to reflect that change and request the package during checkdeps.
=> rpcgen command moved from libc package to rpcsvc-proto in ArchLinux

packages/linux/package.mk
Fixes empty disp_cap due to sanity checking against bad edid info
=> linux: bump amlogic-3.14 to f1e3b08

packages/linux/package.mk
Fixes empty disp_cap due to sanity checking against bad edid info.
Fixes attempts to use display modes not supported by display.
Note: Depends on https://github.com/CoreELEC/linux-amlogic/pull/17
=> Try number two at fixing black screen issues

packages/linux/package.mk
Use new method to set Max TMDS Clock
=> linux: bump amlogic-3.14 to f62840a

packages/mediacenter/kodi-binary-addons/pvr.iptvarchive/package.mk, packages/mediacenter/kodi-binary-addons/pvr.iptvarchive/patches/iptvarchive-0001-add-archive-support.patch, packages/mediacenter/kodi/patches/kodi-ce-009-add-hasarchive-and-isplayable-listitem-apis.patch, packages/mediacenter/kodi/patches/kodi-ce-010-add-pvr-archive-support.patch
This PR adds a modified pvr.iptvsimple add-on and the accompanying modifications to Kodi to support it.
It adds support for the Archive feature some IPTV services provide to their users.
The add-on adds the following improvements over the standard pvr.iptvsimple add-on:
- Support for playing a show from the EPG, using the archive.
- Practically unlimited timeshift support.
- Lets the user select a show from the EPG and timeshift to it.
=> kodi, pvr.iptvarchive: Add support for IPTV Archive features

packages/linux/package.mk, packages/mediacenter/kodi/patches/amlogic/kodi-ce-114-tmp-restore-async-resolution-change.patch, packages/mediacenter/kodi/patches/amlogic/kodi-le-059-frame-rate-fix-for-interlaced.patch, packages/mediacenter/kodi/patches/kodi-ce-002-add-coreelec-settings.patch
Changes required to support the use of the auto switching cs/cd kernel.
Note: Since the auto switching cs/cd changes haven't been merged in the kernel yet. 
There is no kernel bump in this pr.
=> Return auto switching cs/cd

projects/Amlogic/packages/libhybris/patches/libhybris-compile-arch-aarch64.patch
libhybris configure.ac use arm64 to detect arch
CoreELEC use aarch64
=> Fix amlogic libhybris compile problem under arch aarch64

projects/Amlogic/filesystem/usr/sbin/lepotatotoemmc
eMMC timeout should be toggled earlier when installing as we don't want to have the timeout enabled in config.ini copy on eMMC.
=> lepotatoemmc: toggle eMMC timeout earlier

packages/sysutils/amremote/package.mk, packages/sysutils/amremote/scripts/remote-toggle, packages/sysutils/amremote/system.d/amlogic-remote-toggle.service
as discussed previously meson-ir gives a very poor user experience with bundled remotes with generic devices
this service will toggle between meson-ir and amremote for users who wish to use Krypton based remote configurations
=> amremote: add service to toggle between meson-ir/remote

scripts/build
When multiple packages are build simultaneously .la files from first package can already be removed after find call with another and sed fails. Known package to do this is pulse that's why also skip searching it's folder.
=> scripts/build: don't fail on sed with non existent file

packages/sysutils/amremote/scripts/remote-toggle
remote-toggle was not working on device where installtointernal had been used as original version was looking for dtb in /flash which does not exist when installed on internal
I don't know whether this should actually be merged or not or whether we should keep it as things are to discourage using installtointernal
tested on minix u9-h installed to internal
=> amremote: fix remote-toggle when dtb is stored on emmc

packages/mediacenter/kodi/patches/amlogic/kodi-le-062-xbmc_col_conversion_if_0.patch
Kodi PR#15286 improved rendering performance:
https://github.com/xbmc/xbmc/pull/15286
Further tweaks are needed for AML ARM platforms.
As suggest by @kszaq in the above PR.
Noticeable improvements, especially for S912 LE/CE users include:
1) 480/576i mpeg2 SW decoding and YADIF2x deinterlacing is now possible.
2) 720p h264 SW decoding and smooth playback when using Kodi Leia's Netflix Addon is now possible
3) No video playback / external subtitle stuttering observed now with S912 LE / CE
=> Tweak shaders for AML ARM platforms

packages/mediacenter/kodi/patches/amlogic/kodi-up-999-extra-refresh-change-switch-PR15506.patch, packages/mediacenter/kodi/patches/amlogic/kodi-up-999-subs-render-stutter-fix-PR15518.patch
Memphiz patch adds a 4th refresh switching setting "On Start" so Kodi refresh switches on video playback start only. Helps users with slow switching TV's and AVR's and un necessary refresh switching when watching same fps content. Great for watching Netflix TV series. 
Downside - the Kodi GUI will stay at that refresh rate. On my S912 testing it's hardly noticeable, even at 24p.
Kszaq patch - fixes the very first Overlay render -->> video frame upset that occurs when you first activate Subtitles. It's blocked in upstream Kodi at the moment due to a 6+ months old lrusak PR that I doubt will make it into Kodi Leia.
These can always be removed if PR's merged in upstream Kodi.
=> Kodi upstream patches for Subs-video frame stutter & 4th refresh switching option

packages/mediacenter/kodi/patches/kodi-ce-002-add-coreelec-settings.patch
HDMI mute - beneficial for users with old AVR's that need SPDIF only audio
thx @samnazarko 
And Max out the GPU clock for various AML S9xx platforms.
=> CE settings: add mute hdmi audio & Oclock GPU

packages/linux/package.mk, projects/Amlogic/packages/opengl-meson-t82x/package.mk
update to v3.2 Android Open GLES binaries
=> opengl-meson-t82x: bump package to d3e7cfe

projects/Amlogic/bootloader/mkimage
If a user has Android installed on the eMMC rather than our custom u-boot then aml_autoscript is needed on sdcard root to bootup CE.
This was a problem that I introduced in 9.0.1 after 7fb42f7b319bfbcfd6af46a7a66688210090d1f3.
=> projects/Amlogic: copy aml_autoscript into khadas images

projects/Amlogic/packages/u-boot-LePotato/package.mk
As discussed in Slack, it appears LibreComputer is not consistent in it's fabrication of LePotato boards and uses chips of varying specifications, reverted DDR clocks back to original values for maximum compatibility.
=> u-boot-LePotato: bump package to c399719

projects/Amlogic/packages/device-trees-amlogic/package.mk
Sanity checking dtb at bootup in official releases has identified a few minor issues, this fixes an issue identified by @shantigilbert when he was using multidtb on one of his older devices, some dtbs are not present in /usr/share/bootloader/device_trees which causes the sanity check to fail and delay bootup.
=> device-trees-amlogic: add missing dtbs

packages/sysutils/amremote/patches/0001-Team-CoreELEC-Add-support-for-multiple-remote-config.patch
Fixed some compiler warnings
Fixed missing free of allocated memory
Add support for 'custom_begin/custom_end' for multiple remotes
Add example remotes.conf
=> amremote: Add support for multiple remote configs in remote.conf

packages/sysutils/busybox/scripts/init
This PR is to relax DTB sanity check on boot so only official releases are checked, community releases should not be bound by it.
=> busybox: only do dtb sanity check on official releases

packages/sysutils/amremote/system.d/amlogic-remote-toggle.service
As discussed previously, race condition is causing a slow boot on some devices
=> amremote: fix slow boot caused by remote-toggle service

packages/linux/package.mk, packages/sysutils/busybox/scripts/init
this PR adds an additional requirement to the dtb sanity check
as our stats have shown us there is >200 users using old/unsupported dtb's which are not updated when flashing an update tar
the sanity check at bootup will alert users to the fact that they are running an unsupported dtb and delay bootup, this is done in the hope that it will encourage users to update it
by adding the additional check the hope is that this will stop people using old kszaq 8.2 dtb's with coreelec or at the very least alert them that they are using an unsupported dtb
=> add additional requirement to the dtb sanity check

projects/Amlogic/linux/linux.aarch64.conf
"ssh" in cmdline forces SSH server to be on, user should be able to disable it.
This reverts commit 45380490ccd6138a67a33cf9cb1238da7cf10456.
=> Revert "projects/Amlogic: enable SSH by default"

projects/Amlogic/options
Introduced this in my Khadas PR.
The mecool remote map interferes with Philips TV's as KEY_DOWN on Philip's remote corresponds to KEY_POWER in the mecool map.
=> projects/Amlogic: remove mecool from default ir multi map

packages/linux-drivers/RTL8812AU/patches/RTL8812AU-01-fix-build-on-3-14.patch
my bad I only checked that the updated package compiled against 4.9, thanks to @shantigilbert for pointing this out
=> RTL8812AU: fix building package on 3.14

packages/mediacenter/kodi/patches/kodi-999.16-PR15941-fix-GLES-HQ-scalers.patch
This PR adds https://github.com/xbmc/xbmc/pull/15941 to Kodi as the patch is not included in 18.2 final.
Without this patch all "HQ" SW scalers blur instead of sharpen (at least that's how it looks like) - screenshots available in Kodi PR.. I'm not sure if S905/S912 are powerful enough to use HQ scalers but Odroid-N2 should certainly benefit from this patch.
The patch can be dropped if/when merged to Kodi.
=> kodi: add PR15941 to fix GLES HQ scalers
